[book]
authors = ["watcher041"]
language = "en"
multilingual = false
src = "src"
title = "物理学入門"

[output.html]
mathjax-support = false

[preprocessor.katex]
after = ["links"]

# github pagesのため、docs にビルド結果を出力
# mdbook build --dest-dir docs
# 数式は以下のように記載する
# ブロック数式：\$ ～ \$
# インライン数式：$ ～ $